import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">
            Home
          </Link>
          <Link href="/notes">
            Notes
          </Link>
        </nav>
        <main 
          className='w-screen'
        >
          {children}
        </main>
      </body>
    </html>
  )
}
